<?php

declare(strict_types=1);

namespace Kabiroman\Octawire\AuthService\Bundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * Configuration for Octawire Auth Bundle
 */
class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('octawire_auth');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
                ->scalarNode('default_project')
                    ->defaultValue(null)
                    ->info('Default project ID to use when not specified in token')
                ->end()
                ->scalarNode('validation_mode')
                    ->defaultValue('remote')
                    ->validate()
                        ->ifNotInArray(['remote', 'local', 'hybrid'])
                        ->thenInvalid('Validation mode must be "remote", "local" or "hybrid"')
                    ->end()
                    ->info('Token validation mode: remote (via service), local (signature only), hybrid (local + remote blacklist check)')
                ->end()
                ->booleanNode('check_blacklist')
                    ->defaultTrue()
                    ->info('Check token blacklist (only for local/hybrid modes, requires remote call)')
                ->end()
                ->arrayNode('projects')
                    ->isRequired()
                    ->requiresAtLeastOneElement()
                    ->useAttributeAsKey('name')
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('address')
                                ->defaultNull()
                                ->info('Server address (host:port) - deprecated, use tcp.host and tcp.port instead')
                            ->end()
                            ->scalarNode('transport')
                                ->defaultValue('tcp')
                                ->validate()
                                    ->ifNotInArray(['tcp'])
                                    ->thenInvalid('Transport must be "tcp"')
                                ->end()
                                ->info('Transport protocol (currently only "tcp" is supported)')
                            ->end()
                            ->arrayNode('tcp')
                                ->isRequired()
                                ->children()
                                    ->scalarNode('host')
                                        ->isRequired()
                                        ->cannotBeEmpty()
                                        ->info('TCP server host')
                                    ->end()
                                    ->integerNode('port')
                                        ->isRequired()
                                        ->min(1)
                                        ->max(65535)
                                        ->info('TCP server port (default: 50052)')
                                    ->end()
                                    ->booleanNode('persistent')
                                        ->defaultTrue()
                                        ->info('Use persistent connections')
                                    ->end()
                                    ->arrayNode('tls')
                                        ->children()
                                            ->booleanNode('enabled')
                                                ->defaultFalse()
                                                ->info('Enable TLS/mTLS')
                                            ->end()
                                            ->booleanNode('required')
                                                ->defaultFalse()
                                                ->info('Require TLS (fail if TLS not available)')
                                            ->end()
                                            ->scalarNode('cert_file')
                                                ->defaultNull()
                                                ->info('Client certificate file path (for mTLS)')
                                            ->end()
                                            ->scalarNode('key_file')
                                                ->defaultNull()
                                                ->info('Client private key file path (for mTLS)')
                                            ->end()
                                            ->scalarNode('ca_file')
                                                ->defaultNull()
                                                ->info('CA certificate file path')
                                            ->end()
                                            ->scalarNode('server_name')
                                                ->defaultNull()
                                                ->info('Server name for TLS verification')
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                            ->scalarNode('project_id')
                                ->isRequired()
                                ->cannotBeEmpty()
                                ->info('Project ID')
                            ->end()
                            ->scalarNode('api_key')
                                ->defaultNull()
                                ->info('API key for authentication (optional)')
                            ->end()
                            ->arrayNode('service_auth')
                                ->children()
                                    ->scalarNode('service_name')
                                        ->defaultNull()
                                        ->info('Service name for inter-service authentication')
                                    ->end()
                                    ->scalarNode('service_secret')
                                        ->defaultNull()
                                        ->info('Service secret for inter-service authentication')
                                    ->end()
                                ->end()
                                ->info('Service authentication credentials for validateToken and other operations')
                            ->end()
                            ->arrayNode('retry')
                                ->children()
                                    ->integerNode('max_attempts')
                                        ->defaultValue(3)
                                        ->min(1)
                                        ->info('Maximum retry attempts')
                                    ->end()
                                    ->floatNode('initial_backoff')
                                        ->defaultValue(0.1)
                                        ->min(0)
                                        ->info('Initial backoff delay in seconds')
                                    ->end()
                                    ->floatNode('max_backoff')
                                        ->defaultValue(5.0)
                                        ->min(0)
                                        ->info('Maximum backoff delay in seconds')
                                    ->end()
                                ->end()
                            ->end()
                            ->arrayNode('key_cache')
                                ->children()
                                    ->scalarNode('driver')
                                        ->defaultValue('memory')
                                        ->validate()
                                            ->ifNotInArray(['memory', 'redis'])
                                            ->thenInvalid('Driver must be either "memory" or "redis"')
                                        ->end()
                                        ->info('Key cache driver (memory or redis)')
                                    ->end()
                                    ->integerNode('ttl')
                                        ->defaultValue(3600)
                                        ->min(1)
                                        ->info('Key cache TTL in seconds')
                                    ->end()
                                    ->integerNode('max_size')
                                        ->defaultValue(100)
                                        ->min(1)
                                        ->info('Maximum number of projects in cache')
                                    ->end()
                                ->end()
                            ->end()
                            ->arrayNode('redis')
                                ->children()
                                    ->scalarNode('host')
                                        ->defaultValue('localhost')
                                        ->info('Redis host')
                                    ->end()
                                    ->integerNode('port')
                                        ->defaultValue(6379)
                                        ->info('Redis port')
                                    ->end()
                                    ->integerNode('db')
                                        ->defaultValue(0)
                                        ->min(0)
                                        ->info('Redis database number')
                                    ->end()
                                    ->scalarNode('password')
                                        ->defaultNull()
                                        ->info('Redis password (optional)')
                                    ->end()
                                ->end()
                            ->end()
                            ->arrayNode('timeout')
                                ->children()
                                    ->floatNode('connect')
                                        ->defaultValue(10.0)
                                        ->min(0)
                                        ->info('Connection timeout in seconds')
                                    ->end()
                                    ->floatNode('request')
                                        ->defaultValue(30.0)
                                        ->min(0)
                                        ->info('Request timeout in seconds')
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}




